name: reminderassistantbot

services:
  db:
    image: postgres:16
    container_name: reminder_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - reminder_pg:/var/lib/postgresql/data

volumes:
  reminder_pg:
